# .prettierrc.yaml
singleQuote: true
semi: false
printWidth: 110
trailingComma: none

overrides:
  - files: '*.vue'
    options:
      tabWidth: 4
  - files: '*.less'
    options:
      tabWidth: 4
  - files: '*.js'
    options:
      tabWidth: 4
  - files: '*.json'
    options:
      tabWidth: 4
